export const dataTable = [
  // {
  //   IdTransaction: "JSFADFF34F56",
  //   TransactionStatus: "Cobro no realizado",
  //   transactionDate: "04/07/2022 - 12:10:24",
  //   paymentMethod: "**** **** **** 5441",
  //   amount: "25.000",
  //   deduction: null,
  //   deductionAmount: null,
  //   successfulPayment: false,
  //   logoCard: "../assets/images/mc_symbol.svg",
  // },
  // {
  //   IdTransaction: "JSFOOATSFD6F56",
  //   TransactionStatus: "Cobro exitoso",
  //   transactionDate: "04/07/2022 - 13:14:24",
  //   paymentMethod: "**** **** **** 5331",
  //   amount: "80.000",
  //   deduction: "Deducción Bold",
  //   deductionAmount: "15.000",
  //   successfulPayment: true,
  //   logoCard: "../assets/images/visa-4.svg",
  // },
  // {
  //   IdTransaction: "JSFSFF6DLPOF56",
  //   TransactionStatus: "Cobro no realizado",
  //   transactionDate: "04/07/2022 - 18:14:22",
  //   paymentMethod: "**** **** **** 5661",
  //   amount: "80.000",
  //   deduction: null,
  //   deductionAmount: null,
  //   successfulPayment: false,
  //   logoCard: "../assets/images/mc_symbol.svg",
  // },
  // {
  //   IdTransaction: "JSFSPOLHYTSF56",
  //   TransactionStatus: "Cobro exitoso",
  //   transactionDate: "04/07/2022 - 09:15:11",
  //   paymentMethod: "**** **** **** 5111",
  //   amount: "80.000",
  //   deduction: "Deducción Bold",
  //   deductionAmount: "15.000",
  //   successfulPayment: true,
  //   logoCard: "../assets/images/visa-4.svg",
  // },
  {
    IdTransaction: "JSFLMNBYGFT56",
    TransactionStatus: "Cobro exitoso",
    transactionDate: "04/07/2022 - 17:14:24",
    paymentMethod: "**** **** **** 5000",
    amount: "80.000",
    deduction: "Deducción Bold",
    deductionAmount: "15.000",
    successfulPayment: true,
    logoCard: "visa",
  },
  {
    IdTransaction: "FL09JIUE6F56",
    TransactionStatus: "Cobro no realizado",
    transactionDate: "04/07/2022 - 17:14:24",
    paymentMethod: "**** **** **** 5252",
    amount: "100.000",
    deduction: null,
    deductionAmount: null,
    successfulPayment: false,
    logoCard: "mastercard",
  },
  {
    IdTransaction: "QWS6T6DFD6F56",
    TransactionStatus: "Cobro exitoso",
    transactionDate: "04/07/2022 - 17:14:24",
    paymentMethod: "**** **** **** 5252",
    amount: "35.000",
    deduction: "Deducción Bold",
    deductionAmount: "15.000",
    successfulPayment: true,
    logoCard: "mastercard",
  },
  {
    IdTransaction: "QWS6T6DFD6F56",
    TransactionStatus: "Cobro no realizado",
    transactionDate: "04/07/2022 - 17:14:24",
    paymentMethod: "**** **** **** 7771",
    amount: "54.000",
    deduction: null,
    deductionAmount: null,
    successfulPayment: false,
    logoCard: "visa",
  },
  // {
  //   IdTransaction: "QWS6T6DFD6F56",
  //   TransactionStatus: "Cobro exitoso",
  //   transactionDate: "04/07/2022 - 17:19:24",
  //   paymentMethod: "**** **** **** 5771",
  //   amount: "22.000",
  //   deduction: "Deducción Bold",
  //   deductionAmount: "15.000",
  //   successfulPayment: true,
  //   logoCard: "../assets/images/visa-4.svg",
  // },
  // {
  //   IdTransaction: "JS099DHD6F56",
  //   TransactionStatus: "Cobro exitoso",
  //   transactionDate: "04/07/2022 - 17:14:24",
  //   paymentMethod: "**** **** **** 5001",
  //   amount: "65.000",
  //   deduction: "Deducción Bold",
  //   deductionAmount: null,
  //   successfulPayment: true,
  //   logoCard: "../assets/images/mc_symbol.svg",
  // },
];
